### ISSUE TITLE
Running npm start will start webpack and the webpack hot reload server

### ISSUE THREAD

**Issue by TheoMer** [keathley/webpack-react-skeleton#18]
OS: Windows 10 Pro
NPM: version 3.9.5

Ok, So, and having no prior experience of webpack, I'm expecting to receive notification of a url or the opening of a window running the main file in my browser, after running npm start, but alas nothing. 

The steps I take are as follows:
1. git clone https://github.com/keathley/webpack-react-skeleton.git
2. cd webpack-react-skeleton.git
3. npm install
4. webpack
5. npm start

What am I missing here?

**Comment by TheoMer** [comment]
Ok, so I've discovered that webpack can be run in conjunction with gulp, but the problem I'm experiencing is as described here: https://github.com/keathley/webpack-react-skeleton/issues/17

Do you have any plans to configure gulp into your skeleton?

**Comment by keathley** [comment]
I don't have any plans to add gulp since most of what gulp would be handling is managed by webpack and npm scripts. If you just run `npm start` webpacks announces that its running on `http://localhost:8080`. However, it gets quickly hidden by the rest of the output from webpack so I understand how it could be confusing.

I've updated all the packages and resolved some issues so you should be able to pull down master and get things going again. Sorry about the issues.
